### ISSUE TITLE
jQuery Dependency?

### ISSUE THREAD

**Issue by eroh92** [zachsnow/ng-elif#10]
Hey this is a great idea, especially since `ng-if` flickers a bit so I end up putting this logic in the controllers. Is the `$` in `getBlockElements` a jQuery dependency though?

**Comment by zachsnow** [comment]
That is a good question; I think it could be `angular.element`, will investigate.

**Comment by rehmsen** [comment]
Could you publish a new version so that we get this fix? I am for now depending on the commit hash, but it would be nicer for this to become 0.1.4 or something.

**Comment by zachsnow** [comment]
@rehmsen done.

**Comment by rehmsen** [comment]
Thanks!
