### ISSUE TITLE
Nesting tests inside <p> element fails

### ISSUE THREAD

**Issue by anodynos** [zachsnow/ng-elif#11]
In the following simplified example (based on http://plnkr.co/edit/XSPP3jZL8eehu9G750ME?p=preview), having the `if/else` structure inside `<p>...</p>` fails (both if and else branches are executed). 

If you remove the `<p>` (or indeed convert the opening `<p>` to a self closing `</p>`) solves the problem. Any idea ?
```
  <body ng-controller="ctrl" ng-init="test1 = true">
    <a class="test" ng-toggle="test1">test1 {{ test1 }}</a>

    &larr; <i>Click the tabs, eh?</i>

      <p>

      <span class="case" ng-if="test1">
        <h1>if(test1) is true</h1>
        <p>
          This is the if block, which matches because <code>test1</code> is
          true
        </p>
      </span >
      
      <span  ng-else>
        <h1>if(test1) is false </h1>
      </span>

    </p>

  </body>
```

See http://plnkr.co/edit/YUEuQGgprRojrwQm2RMP?p=preview

**Comment by zachsnow** [comment]
I guess this is because nested `<p>` elements is not valid. The browser is rearranging things under the hood so you end up with 3 `<p>` elements and everything is bonkers.
