### ISSUE TITLE
npm?

### ISSUE THREAD

**Issue by peterugh** [zachsnow/ng-elif#13]
Have you considered adding to npm? Would you like someone else to make that possible? I know this isn't really an "issue" but I don't know where else to put this.

**Comment by zachsnow** [comment]
Hey @peterugh npm sounds fine, just wasn't something I needed. I'll get that out this weekend.

**Comment by zachsnow** [comment]
Too slow, apologies. Today!

**Comment by peterugh** [comment]
No worries! 

-Pete Rugh
/////////////////////////////////

**Comment by zachsnow** [comment]
Ok, I did `npm publish` but I don't really know what I'm doing so we'll see.
