### ISSUE TITLE
How does this library internally work?

### ISSUE THREAD

**Issue by akcasoy** [zachsnow/ng-elif#14]
Will the else conditions still be evaluated internally when the if condition was already true? This is based on my stackoverflow question: http://stackoverflow.com/questions/33540326/how-do-handle-if-else-cases-in-angular-ng-show-without-ng-switch?noredirect=1#comment54866854_33540326

if(x) {
}
else if(y){
}

Will this internally be converted to this?:

if(x) {
}
if(!x && y){
}

.. so will the x condition be evaluated twice?

**Comment by zachsnow** [comment]
Hey @akcasoy, what happens is that the expressions `x` and `y` are stored, and then each digest they are evaluated. So, `x` and `y` are each evaluated once. Note that this is much different than a "real" if-else in, say, Javascript, wherein when `x` is true `y` is not evaluated at all.

**Comment by akcasoy** [comment]
Then what is the advantage of this library when we have to evaluate the expressions of unneeded cases? So you basically convert the if else statement to this:

if(x) {
}
if(!x && y){
}

where you evaluate both x and y.  But the second 'if' never be true if the first one was true. So it will act like an if/else. But technically it is not sth special. Do i understand right?

**Comment by zachsnow** [comment]
No, we only evaluate `x` once and `y` once. You could think of it like this:

```javascript
if(x){ ... }
else if(y){ ... }
else { ... }
```

Becomes:
```javascript
var evaluatedX = x;
var evaluatedY = y;

if(evaluatedX){ ... }
else if(evaluatedY){ ... }
else { ... }
```

**Comment by zachsnow** [comment]
See https://github.com/zachsnow/ng-elif/blob/master/src/elif.js#L52-L61 for a clearer understanding.  It doesn't seem like it would be too hard to change it to be more like an if/else in a sequential programming language, I just haven't needed to yet.

**Comment by zachsnow** [comment]
@akcasoy see `dev/short-circuit` for a short-circuiting version of `ng-elif`; I will likely publish this today but in case I don't get a chance.

**Comment by akcasoy** [comment]
"I avoid writing conditions that are expensive to compute"
i would like to know how i can decide not to write complex conditions :) That is for me not a decision but a "need". I need complex conditions, i have complex conditions, i dont have any other option. So i would like to skip evaluating else conditions. Thank you for your time and answers though. I will have a close look at your project when i have time..
