### ISSUE TITLE
Not working like a regular if/else stmt

### ISSUE THREAD

**Issue by AliHichem** [zachsnow/ng-elif#7]
when using code like this 
```
<h1 ng-if="1 == 1">1...</h1>
<h1 ng-elif="2 == 2">2...</h1>
<h1 ng-else>3...</h1>
```
I should only get the first case executed but in this case I get all of them executed and I see at the end "1...2...3..."
accodring to a regular if/else from any programming language that should only stops on the first valid condition , for instance:
```
php > if (1==1) echo 1; else if (2==2) echo 2; else echo 3;
1
```
it shows only "1" which is the first valid condition.

Thanks for fixing this !

**Comment by zachsnow** [comment]
You make a good point :P

I'll fix this.

**Comment by zachsnow** [comment]
@AliHichem in reviewing this I wasn't actually able to reproduce the issue. Code I tried:

      <div ng-if="1 == 1">
        One equals 1.
      </div>
      <div ng-elif="2 == 2">
        Two equals 2.
      </div>
      <div ng-else>
        Something crazy.
      </div>

**Comment by AliHichem** [comment]
Actually It was exactly what I wanted to check before using this plugin. So I did exactly try with 
```
<h1 ng-if="1 == 1">1...</h1>
<h1 ng-elif="2 == 2">2...</h1>
<h1 ng-else>3...</h1>
```
and it does seem to be working , also with the piece of code your tried I get this as a result 
```
 One equals 1.
Two equals 2.
Something crazy. 
```
I'm using AngularJS v1.2.25 btw. Tried it with firefow and chrome and I encounter the issue with both browsers

**Comment by zachsnow** [comment]
Is there any chance the module isn't being properly loaded? Sounds like what would happen if `ng-elif` and `ng-else` weren't actually available as directives perhaps.

**Comment by zachsnow** [comment]
Check out the bottom of this demo to see how I tested it out: http://plnkr.co/edit/XSPP3jZL8eehu9G750ME?p=preview

**Comment by AliHichem** [comment]
My bad, it was indeed not load ... I feel so lame , I'm very sorry ^^.
But if a module isn't loaded, shouldn't be there something like a console error ? 
anyway this is fixed for me , it was just my fault . Really nice work !
