### ISSUE TITLE
Button Events not Firing When Using If-Else

### ISSUE THREAD

**Issue by pbtura** [zachsnow/ng-elif#9]
When button tags are included/excluded from html using ng-if and ng-else, ng-click events defined for the 'else' button  never fire. Take a look at the plunker here: (http://plnkr.co/edit/q6GEaKsSVd5KONVUS3zO?p=preview) for an example.

**Comment by zachsnow** [comment]
Apparently I don't know how to spell `priority`. Will fix.

**Comment by zachsnow** [comment]
Fixed and released in version 0.1.3.
